# Generated by Django 2.2.7 on 2019-11-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='published date')),
                ('category', models.CharField(choices=[('K', 'Kosulje'), ('P', 'Pantalone'), ('J', 'Jakne'), ('DZ', 'Dzemperi'), ('M', 'Majice'), ('T', 'Trenerke'), ('D', 'Duskevi'), ('A', 'Aksesoari')], max_length=2)),
                ('price', models.IntegerField()),
                ('sale', models.BooleanField(default=False)),
                ('discout', models.IntegerField(default=0)),
                ('size', models.IntegerField()),
                ('chest', models.IntegerField()),
                ('length', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('colors', models.TextField(max_length=120)),
            ],
        ),
    ]
