# Generated by Django 2.2.7 on 2019-11-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL'), ('7XL', '7XL'), ('8XL', '8XL'), ('9XL', '9XL'), ('10XL', '10XL')], max_length=4),
        ),
    ]
