# Generated by Django 2.2.7 on 2019-11-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20191109_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL'), ('7XL', '7XL'), ('8XL', '8XL'), ('9XL', '9XL'), ('10XL', '10XL')], max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(choices=[('R', 'red'), ('G', 'green'), ('B', 'blue'), ('Y', 'yellow'), ('G', 'green'), ('S', 'silver'), ('C', 'cyan'), ('BL', 'black'), ('W', 'white'), ('T', 'teal'), ('BG', 'beige')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='website.Size'),
        ),
    ]
