# Generated by Django 2.2.7 on 2019-11-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20191110_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('message', models.TextField()),
            ],
        ),
    ]
